<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:tal="http://xml.zope.org/namespaces/tal">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>${project} Application</title>
<meta name="keywords" content="python web application" />
<meta name="description" content="Pylons web application" />
<link href="${request.application_url}/static/default.css" rel="stylesheet" type="text/css" />
</head>
<body>
<!-- start header -->
<div id="logo">
  <h2><code>${project}</code>, a <code>Pylons</code> application</h2>
</div>
<div id="header">
  <div id="menu">
  </div>
</div>
<!-- end header -->
<div id="wrapper">
  <!-- start page -->
  <div id="page">
    <!-- start content -->
    <div id="content">
      <div class="post">
	<h1 class="title">Welcome to <code>${project}</code>, an
	application generated by the <a
	href="http://pylonshq.com">Pylons</a> web
	application framework.</h1>
      </div>
      <div>The root object's name is "${root.name}"</div>
    </div>
    <!-- end content -->
    <!-- start sidebar -->
    <div id="sidebar"></div>
    <!-- end sidebar -->
    <div style="clear: both;">&nbsp;</div>
  </div>
</div>
<!-- end page -->
<!-- start footer -->
<div id="footer">
  <p id="legal">( c ) 2008. All Rights Reserved. Template design
  by <a href="http://www.freecsstemplates.org/">Free CSS
  Templates</a>.</p>
</div>
<!-- end footer -->
</body>
</html>
